com: 
  zipkin: 
    serviceName: USER-SERVICE
    url: http://localhost:9411
    connectTimeout: 10000
    readTimeout: 1000
    flushInterval: 1000
    compressionEnabled: true
    endpoint: http://127.0.0.1:9411/api/v2/spans
    
name: fancyallenwu
# 端口信息
server:
  port: 10000
# 应用名称
spring:
  application:
    name: USER-SERVICE
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/test?statementInterceptors=brave.mysql.TracingStatementInterceptor
    username: root
    password: 123
    driverClassName: com.mysql.jdbc.Driver
# 日志级别
logging:
  level:
    key : info
  config: classpath:logback-spring.xml


eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka-server-01:7001/eureka/


  
