name: fancyallenwu
# 端口信息
server:
  port: 10000
# 应用名称
spring:
  application:
    name: USER-SERVICE
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
# 日志级别
logging:
  level:
    key : info
  config: classpath:logback-spring.xml


eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka-server-01:7001/eureka/
